2018-05-08T22:03:18.7182655+02:00 0HLDL3QURF7BN:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/   (ca22a1cb)
2018-05-08T22:03:22.3640662+02:00 0HLDL3QURF7BN:00000001 [INF] Executing action method "Inventory.Web.Controllers.HomeController.Index (Inventory.Web)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-05-08T22:03:34.0638847+02:00 0HLDL3QURF7BN:00000001 [INF] Executing ViewResult, running view at path "/Views/Home/Index.cshtml". (9707eebe)
2018-05-08T22:03:37.0770276+02:00 0HLDL3QURF7BP:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/css/site.css   (ca22a1cb)
2018-05-08T22:03:37.2044497+02:00 0HLDL3QURF7BO:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/bootstrap/dist/css/bootstrap.css   (ca22a1cb)
2018-05-08T22:03:37.2704268+02:00 0HLDL3QURF7BN:00000001 [INF] Executed action "Inventory.Web.Controllers.HomeController.Index (Inventory.Web)" in 14719.9297ms (afa2e885)
2018-05-08T22:03:37.4276733+02:00 0HLDL3QURF7BP:00000001 [INF] Sending file. Request path: '"/css/site.css"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\css\site.css"' (27b0a520)
2018-05-08T22:03:37.4669218+02:00 0HLDL3QURF7BQ:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/images/banner1.svg   (ca22a1cb)
2018-05-08T22:03:37.5091024+02:00 0HLDL3QURF7BT:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/images/banner4.svg   (ca22a1cb)
2018-05-08T22:03:37.5420519+02:00 0HLDL3QURF7BO:00000001 [INF] Sending file. Request path: '"/lib/bootstrap/dist/css/bootstrap.css"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\lib\bootstrap\dist\css\bootstrap.css"' (27b0a520)
2018-05-08T22:03:37.5828155+02:00 0HLDL3QURF7BN:00000001 [INF] Request finished in 18908.4819ms 200 text/html; charset=utf-8 (791a596a)
2018-05-08T22:03:37.6505392+02:00 0HLDL3QURF7BQ:00000001 [INF] Sending file. Request path: '"/images/banner1.svg"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\images\banner1.svg"' (27b0a520)
2018-05-08T22:03:37.6639284+02:00 0HLDL3QURF7BT:00000001 [INF] Sending file. Request path: '"/images/banner4.svg"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\images\banner4.svg"' (27b0a520)
2018-05-08T22:03:37.6778935+02:00 0HLDL3QURF7BS:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/images/banner3.svg   (ca22a1cb)
2018-05-08T22:03:37.7400104+02:00 0HLDL3QURF7BR:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/images/banner2.svg   (ca22a1cb)
2018-05-08T22:03:37.8248549+02:00 0HLDL3QURF7BS:00000001 [INF] Sending file. Request path: '"/images/banner3.svg"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\images\banner3.svg"' (27b0a520)
2018-05-08T22:03:37.9273050+02:00 0HLDL3QURF7BU:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/bootstrap/dist/js/bootstrap.js   (ca22a1cb)
2018-05-08T22:03:37.9555386+02:00 0HLDL3QURF7C0:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/js/site.js?v=ji3-IxbEzYWjzzLCGkF1KDjrT2jLbbrSYXw-AhMPNIA   (ca22a1cb)
2018-05-08T22:03:37.9744169+02:00 0HLDL3QURF7BV:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/jquery/dist/jquery.js   (ca22a1cb)
2018-05-08T22:03:38.0217958+02:00 0HLDL3QURF7BP:00000001 [INF] Request finished in 886.8169ms 200 text/css (791a596a)
2018-05-08T22:03:38.0387390+02:00 0HLDL3QURF7BR:00000001 [INF] Sending file. Request path: '"/images/banner2.svg"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\images\banner2.svg"' (27b0a520)
2018-05-08T22:03:38.4155154+02:00 0HLDL3QURF7BV:00000001 [INF] Sending file. Request path: '"/lib/jquery/dist/jquery.js"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\lib\jquery\dist\jquery.js"' (27b0a520)
2018-05-08T22:03:38.4997108+02:00 0HLDL3QURF7BU:00000001 [INF] Sending file. Request path: '"/lib/bootstrap/dist/js/bootstrap.js"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\lib\bootstrap\dist\js\bootstrap.js"' (27b0a520)
2018-05-08T22:03:38.5592850+02:00 0HLDL3QURF7BR:00000001 [INF] Request finished in 540.0665ms 200 image/svg+xml (791a596a)
2018-05-08T22:03:38.5693597+02:00 0HLDL3QURF7C0:00000001 [INF] Sending file. Request path: '"/js/site.js"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\js\site.js"' (27b0a520)
2018-05-08T22:03:38.7683441+02:00 0HLDL3QURF7BT:00000001 [INF] Request finished in 1395.987ms 200 image/svg+xml (791a596a)
2018-05-08T22:03:38.7743058+02:00 0HLDL3QURF7BQ:00000001 [INF] Request finished in 1266.0282ms 200 image/svg+xml (791a596a)
2018-05-08T22:03:38.8081924+02:00 0HLDL3QURF7BS:00000001 [INF] Request finished in 913.8233ms 200 image/svg+xml (791a596a)
2018-05-08T22:03:39.2367041+02:00 0HLDL3QURF7BO:00000001 [INF] Request finished in 1860.967ms 200 text/css (791a596a)
2018-05-08T22:03:39.3903669+02:00 0HLDL3QURF7BU:00000001 [INF] Request finished in 939.5067ms 200 application/javascript (791a596a)
2018-05-08T22:03:39.4782257+02:00 0HLDL3QURF7C0:00000001 [INF] Request finished in 1111.1887ms 200 application/javascript (791a596a)
2018-05-08T22:03:39.6218035+02:00 0HLDL3QURF7BN:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2   (ca22a1cb)
2018-05-08T22:03:39.6428226+02:00 0HLDL3QURF7BV:00000001 [INF] Request finished in 1809.1276ms 200 application/javascript (791a596a)
2018-05-08T22:03:39.6664856+02:00 0HLDL3QURF7BN:00000002 [INF] Sending file. Request path: '"/lib/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\lib\bootstrap\dist\fonts\glyphicons-halflings-regular.woff2"' (27b0a520)
2018-05-08T22:03:39.8324544+02:00 0HLDL3QURF7BN:00000002 [INF] Request finished in 550.2818ms 200 font/woff2 (791a596a)
2018-05-08T22:03:39.9119196+02:00 0HLDL3QURF7BP:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44391/favicon.ico   (ca22a1cb)
2018-05-08T22:03:39.9575908+02:00 0HLDL3QURF7BP:00000002 [INF] Sending file. Request path: '"/favicon.ico"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\favicon.ico"' (27b0a520)
2018-05-08T22:03:40.1861253+02:00 0HLDL3QURF7BP:00000002 [INF] Request finished in 213.0736ms 200 image/x-icon (791a596a)
2018-05-08T22:03:40.2436310+02:00 0HLDL3QURF7BR:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44391/favicon.ico   (ca22a1cb)
2018-05-08T22:03:40.3035967+02:00 0HLDL3QURF7BR:00000002 [INF] Sending file. Request path: '"/favicon.ico"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\favicon.ico"' (27b0a520)
2018-05-08T22:03:40.3716713+02:00 0HLDL3QURF7BR:00000002 [INF] Request finished in 322.5057ms 200 image/x-icon (791a596a)
2018-05-08T22:03:56.9884467+02:00 0HLDL3QURF7BQ:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44391/C   (ca22a1cb)
2018-05-08T22:03:57.1557106+02:00 0HLDL3QURF7BQ:00000002 [INF] Request finished in 28.8163ms 404  (791a596a)
2018-05-08T22:04:00.4572794+02:00 0HLDL3QURF7BT:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44391/Category/Create   (ca22a1cb)
2018-05-08T22:04:00.5128650+02:00 0HLDL3QURF7BT:00000002 [INF] Executing action method "Inventory.Web.Controllers.CategoryController.Create (Inventory.Web)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-05-08T22:04:01.8873773+02:00 0HLDL3QURF7BT:00000002 [INF] Executing ViewResult, running view at path "/Views/Category/Create.cshtml". (9707eebe)
2018-05-08T22:04:03.3838464+02:00 0HLDL3QURF7BT:00000002 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Create (Inventory.Web)" in 2846.0703ms (afa2e885)
2018-05-08T22:04:03.5658134+02:00 0HLDL3QURF7BT:00000002 [INF] Request finished in 3018.2626ms 200 text/html; charset=utf-8 (791a596a)
2018-05-08T22:04:03.6479613+02:00 0HLDL3QURF7BU:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/jquery-validation/dist/jquery.validate.js   (ca22a1cb)
2018-05-08T22:04:03.6873366+02:00 0HLDL3QURF7BS:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js   (ca22a1cb)
2018-05-08T22:04:03.7029859+02:00 0HLDL3QURF7BU:00000002 [INF] Sending file. Request path: '"/lib/jquery-validation/dist/jquery.validate.js"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\lib\jquery-validation\dist\jquery.validate.js"' (27b0a520)
2018-05-08T22:04:03.7951636+02:00 0HLDL3QURF7BS:00000002 [INF] Sending file. Request path: '"/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\lib\jquery-validation-unobtrusive\jquery.validate.unobtrusive.js"' (27b0a520)
2018-05-08T22:04:03.8051170+02:00 0HLDL3QURF7BU:00000002 [INF] Request finished in 211.6633ms 200 application/javascript (791a596a)
2018-05-08T22:04:03.8586345+02:00 0HLDL3QURF7BS:00000002 [INF] Request finished in 309.1396ms 200 application/javascript (791a596a)
2018-05-08T22:04:17.3484705+02:00 0HLDL3QURF7C0:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44391/Category   (ca22a1cb)
2018-05-08T22:04:17.3681884+02:00 0HLDL3QURF7C0:00000002 [INF] Executing action method "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-05-08T22:04:18.5328693+02:00 0HLDL3QURF7C0:00000002 [INF] Executing ViewResult, running view at path "/Views/Category/Index.cshtml". (9707eebe)
2018-05-08T22:04:19.0900657+02:00 0HLDL3QURF7C0:00000002 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" in 1722.4886ms (afa2e885)
2018-05-08T22:04:19.8404010+02:00 0HLDL3QURF7C0:00000002 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.NullReferenceException: Object reference not set to an instance of an object.
   at AspNetCore._Views_Category_Index_cshtml.<ExecuteAsync>d__8.MoveNext() in C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\Views\Category\Index.cshtml:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageCoreAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-05-08T22:04:20.8767429+02:00 0HLDL3QURF7C0:00000002 [INF] Request finished in 3466.3126ms 500 text/html; charset=utf-8 (791a596a)
2018-05-08T22:23:41.5370161+02:00 0HLDL46BBNTC5:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/   (ca22a1cb)
2018-05-08T22:23:43.2211136+02:00 0HLDL46BBNTC5:00000001 [INF] Executing action method "Inventory.Web.Controllers.HomeController.Index (Inventory.Web)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-05-08T22:23:50.6812835+02:00 0HLDL46BBNTC5:00000001 [INF] Executing ViewResult, running view at path "/Views/Home/Index.cshtml". (9707eebe)
2018-05-08T22:23:53.5612307+02:00 0HLDL46BBNTC5:00000001 [INF] Executed action "Inventory.Web.Controllers.HomeController.Index (Inventory.Web)" in 10211.7731ms (afa2e885)
2018-05-08T22:23:53.8582130+02:00 0HLDL46BBNTC5:00000001 [INF] Request finished in 12272.338ms 200 text/html; charset=utf-8 (791a596a)
2018-05-08T22:24:00.8536022+02:00 0HLDL46BBNTC5:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44391/Category/Index   (ca22a1cb)
2018-05-08T22:24:00.8975876+02:00 0HLDL46BBNTC5:00000002 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" in 7.3116ms (afa2e885)
2018-05-08T22:24:01.2521024+02:00 0HLDL46BBNTC5:00000002 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.InvalidOperationException: Unable to resolve service for type 'Inventory.Services.Interfaces.ICategoryService' while attempting to activate 'Inventory.Web.Controllers.CategoryController'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-05-08T22:24:02.1544095+02:00 0HLDL46BBNTC5:00000002 [INF] Request finished in 1269.8432ms 500 text/html; charset=utf-8 (791a596a)
2018-05-08T22:27:01.6975564+02:00 0HLDL486UR4RH:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/   (ca22a1cb)
2018-05-08T22:27:03.2760740+02:00 0HLDL486UR4RH:00000001 [INF] Executing action method "Inventory.Web.Controllers.HomeController.Index (Inventory.Web)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-05-08T22:27:12.7900035+02:00 0HLDL486UR4RJ:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/Category/Index   (ca22a1cb)
2018-05-08T22:27:12.8904416+02:00 0HLDL486UR4RJ:00000001 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" in 13.7226ms (afa2e885)
2018-05-08T22:27:13.5426376+02:00 0HLDL486UR4RJ:00000001 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.InvalidOperationException: Unable to resolve service for type 'Inventory.Services.Interfaces.ICategoryService' while attempting to activate 'Inventory.Web.Controllers.CategoryController'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-05-08T22:27:15.3971952+02:00 0HLDL486UR4RH:00000001 [INF] Executing ViewResult, running view at path "/Views/Home/Index.cshtml". (9707eebe)
2018-05-08T22:27:15.4968880+02:00 0HLDL486UR4RJ:00000001 [INF] Request finished in 2717.6673ms 500 text/html; charset=utf-8 (791a596a)
2018-05-08T22:27:17.3718596+02:00 0HLDL486UR4RH:00000001 [INF] Executed action "Inventory.Web.Controllers.HomeController.Index (Inventory.Web)" in 14341.3561ms (afa2e885)
2018-05-08T22:27:17.3907248+02:00 0HLDL486UR4RH:00000001 [INF] Committing the session was canceled. (12038ba6)
2018-05-08T22:27:17.4086057+02:00 0HLDL486UR4RH:00000001 [INF] Request finished in 15963.6304ms 200 text/html; charset=utf-8 (791a596a)
2018-05-08T22:33:08.6006004+02:00 0HLDL4BKACS45:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/   (ca22a1cb)
2018-05-08T22:33:10.3233103+02:00 0HLDL4BKACS45:00000001 [INF] Executing action method "Inventory.Web.Controllers.HomeController.Index (Inventory.Web)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-05-08T22:33:12.6593670+02:00 0HLDL4BKACS47:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/Category/Index   (ca22a1cb)
2018-05-08T22:33:12.7611288+02:00 0HLDL4BKACS47:00000001 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" in 29.5667ms (afa2e885)
2018-05-08T22:33:13.2307495+02:00 0HLDL4BKACS47:00000001 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.InvalidOperationException: Unable to resolve service for type 'Inventory.Services.Interfaces.ICategoryService' while attempting to activate 'Inventory.Web.Controllers.CategoryController'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-05-08T22:33:14.2145378+02:00 0HLDL4BKACS47:00000001 [INF] Request finished in 1503.5098ms 500 text/html; charset=utf-8 (791a596a)
2018-05-08T22:33:19.0239792+02:00 0HLDL4BKACS45:00000001 [INF] Executing ViewResult, running view at path "/Views/Home/Index.cshtml". (9707eebe)
2018-05-08T22:33:21.3936573+02:00 0HLDL4BKACS45:00000001 [INF] Executed action "Inventory.Web.Controllers.HomeController.Index (Inventory.Web)" in 10999.4974ms (afa2e885)
2018-05-08T22:33:21.5065503+02:00 0HLDL4BKACS45:00000001 [INF] Request finished in 12972.1298ms 200 text/html; charset=utf-8 (791a596a)
2018-05-08T22:33:22.9074896+02:00 0HLDL4BKACS47:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44391/Category/Index   (ca22a1cb)
2018-05-08T22:33:22.9282340+02:00 0HLDL4BKACS47:00000002 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" in 3.7078ms (afa2e885)
2018-05-08T22:33:23.1495636+02:00 0HLDL4BKACS47:00000002 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.InvalidOperationException: Unable to resolve service for type 'Inventory.Services.Interfaces.ICategoryService' while attempting to activate 'Inventory.Web.Controllers.CategoryController'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-05-08T22:33:23.5284274+02:00 0HLDL4BKACS47:00000002 [INF] Request finished in 518.8054ms 500 text/html; charset=utf-8 (791a596a)
2018-05-08T22:36:02.5638116+02:00 0HLDL4D86J9JK:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/   (ca22a1cb)
2018-05-08T22:36:04.2725493+02:00 0HLDL4D86J9JK:00000001 [INF] Executing action method "Inventory.Web.Controllers.HomeController.Index (Inventory.Web)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-05-08T22:36:05.5932504+02:00 0HLDL4D86J9JL:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/Category/Index   (ca22a1cb)
2018-05-08T22:36:05.6591695+02:00 0HLDL4D86J9JL:00000001 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" in 11.5205ms (afa2e885)
2018-05-08T22:36:06.2285197+02:00 0HLDL4D86J9JL:00000001 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.InvalidOperationException: Unable to resolve service for type 'Inventory.Services.Interfaces.ICategoryService' while attempting to activate 'Inventory.Web.Controllers.CategoryController'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-05-08T22:36:07.6189652+02:00 0HLDL4D86J9JL:00000001 [INF] Request finished in 1992.0286ms 500 text/html; charset=utf-8 (791a596a)
2018-05-08T22:36:12.2237302+02:00 0HLDL4D86J9JK:00000001 [INF] Executing ViewResult, running view at path "/Views/Home/Index.cshtml". (9707eebe)
2018-05-08T22:36:14.0449279+02:00 0HLDL4D86J9JK:00000001 [INF] Executed action "Inventory.Web.Controllers.HomeController.Index (Inventory.Web)" in 9910.0747ms (afa2e885)
2018-05-08T22:36:14.0639537+02:00 0HLDL4D86J9JK:00000001 [INF] Committing the session was canceled. (12038ba6)
2018-05-08T22:36:14.0885126+02:00 0HLDL4D86J9JK:00000001 [INF] Request finished in 11648.8878ms 200 text/html; charset=utf-8 (791a596a)
2018-05-08T22:36:15.1788367+02:00 0HLDL4D86J9JL:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44391/Category/Index   (ca22a1cb)
2018-05-08T22:36:15.1999895+02:00 0HLDL4D86J9JL:00000002 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" in 2.5455ms (afa2e885)
2018-05-08T22:36:15.4328970+02:00 0HLDL4D86J9JL:00000002 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.InvalidOperationException: Unable to resolve service for type 'Inventory.Services.Interfaces.ICategoryService' while attempting to activate 'Inventory.Web.Controllers.CategoryController'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-05-08T22:36:15.7644575+02:00 0HLDL4D86J9JL:00000002 [INF] Request finished in 541.1372ms 500 text/html; charset=utf-8 (791a596a)
2018-05-08T22:36:50.3935946+02:00 0HLDL4D86J9JL:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:44391/Category/Index   (ca22a1cb)
2018-05-08T22:36:50.4516399+02:00 0HLDL4D86J9JL:00000003 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" in 10.6132ms (afa2e885)
2018-05-08T22:36:50.7378360+02:00 0HLDL4D86J9JL:00000003 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.InvalidOperationException: Unable to resolve service for type 'Inventory.Services.Interfaces.ICategoryService' while attempting to activate 'Inventory.Web.Controllers.CategoryController'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-05-08T22:36:51.1648771+02:00 0HLDL4D86J9JL:00000003 [INF] Request finished in 680.5184ms 500 text/html; charset=utf-8 (791a596a)
2018-05-08T22:36:56.9991419+02:00 0HLDL4D86J9JL:00000004 [INF] Request starting HTTP/1.1 GET http://localhost:44391/Category/Index   (ca22a1cb)
2018-05-08T22:36:57.0134343+02:00 0HLDL4D86J9JL:00000004 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" in 1.7445ms (afa2e885)
2018-05-08T22:36:57.2383250+02:00 0HLDL4D86J9JL:00000004 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.InvalidOperationException: Unable to resolve service for type 'Inventory.Services.Interfaces.ICategoryService' while attempting to activate 'Inventory.Web.Controllers.CategoryController'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-05-08T22:36:57.6252371+02:00 0HLDL4D86J9JL:00000004 [INF] Request finished in 540.163ms 500 text/html; charset=utf-8 (791a596a)
2018-05-08T22:39:59.7040892+02:00 0HLDL4FES00KN:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/Category/Index   (ca22a1cb)
2018-05-08T22:40:01.2606994+02:00 0HLDL4FES00KN:00000001 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" in 44.1231ms (afa2e885)
2018-05-08T22:40:01.6288332+02:00 0HLDL4FES00KN:00000001 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.InvalidOperationException: Unable to resolve service for type 'Inventory.Services.Interfaces.ICategoryService' while attempting to activate 'Inventory.Web.Controllers.CategoryController'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-05-08T22:40:02.5427455+02:00 0HLDL4FES00KN:00000001 [INF] Request finished in 2922.6779ms 500 text/html; charset=utf-8 (791a596a)
2018-05-08T22:40:08.5276788+02:00 0HLDL4FES00KN:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44391/Category/Index   (ca22a1cb)
2018-05-08T22:40:08.5473744+02:00 0HLDL4FES00KN:00000002 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" in 2.6139ms (afa2e885)
2018-05-08T22:40:08.7879265+02:00 0HLDL4FES00KN:00000002 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.InvalidOperationException: Unable to resolve service for type 'Inventory.Services.Interfaces.ICategoryService' while attempting to activate 'Inventory.Web.Controllers.CategoryController'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-05-08T22:40:09.1090895+02:00 0HLDL4FES00KN:00000002 [INF] Request finished in 504.4033ms 500 text/html; charset=utf-8 (791a596a)
2018-05-08T22:40:12.2443648+02:00 0HLDL4FES00KN:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:44391/Category/Index   (ca22a1cb)
2018-05-08T22:40:12.2630518+02:00 0HLDL4FES00KN:00000003 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" in 2.0977ms (afa2e885)
2018-05-08T22:40:12.5369325+02:00 0HLDL4FES00KN:00000003 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.InvalidOperationException: Unable to resolve service for type 'Inventory.Services.Interfaces.ICategoryService' while attempting to activate 'Inventory.Web.Controllers.CategoryController'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-05-08T22:40:12.7546658+02:00 0HLDL4FES00KN:00000003 [INF] Request finished in 489.1337ms 500 text/html; charset=utf-8 (791a596a)
2018-05-08T22:42:17.9226619+02:00 0HLDL4GO15OU8:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/Category/Index   (ca22a1cb)
2018-05-08T22:42:17.9226614+02:00 0HLDL4GO15OU7:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/   (ca22a1cb)
2018-05-08T22:42:19.7986608+02:00 0HLDL4GO15OU8:00000001 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" in 81.9264ms (afa2e885)
2018-05-08T22:42:19.9401235+02:00 0HLDL4GO15OU7:00000001 [INF] Executing action method "Inventory.Web.Controllers.HomeController.Index (Inventory.Web)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-05-08T22:42:20.4173325+02:00 0HLDL4GO15OU8:00000001 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.InvalidOperationException: Unable to resolve service for type 'Inventory.Services.Interfaces.ICategoryService' while attempting to activate 'Inventory.Web.Controllers.CategoryController'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-05-08T22:42:21.8918571+02:00 0HLDL4GO15OU8:00000001 [INF] Request finished in 4057.1566ms 500 text/html; charset=utf-8 (791a596a)
2018-05-08T22:42:28.3108754+02:00 0HLDL4GO15OU7:00000001 [INF] Executing ViewResult, running view at path "/Views/Home/Index.cshtml". (9707eebe)
2018-05-08T22:42:30.8166853+02:00 0HLDL4GO15OU7:00000001 [INF] Executed action "Inventory.Web.Controllers.HomeController.Index (Inventory.Web)" in 10781.3172ms (afa2e885)
2018-05-08T22:42:31.0654389+02:00 0HLDL4GO15OU7:00000001 [INF] Request finished in 13122.0734ms 200 text/html; charset=utf-8 (791a596a)
2018-05-08T22:53:30.0396896+02:00 0HLDL4N066855:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:51686/   (ca22a1cb)
2018-05-08T22:53:31.4352491+02:00 0HLDL4N066855:00000001 [INF] Executing action method "Inventory.Web.Controllers.HomeController.Index (Inventory.Web)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-05-08T22:53:38.0596309+02:00 0HLDL4N066855:00000001 [INF] Executing ViewResult, running view at path "/Views/Home/Index.cshtml". (9707eebe)
2018-05-08T22:53:40.6429687+02:00 0HLDL4N066856:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:51686/lib/bootstrap/dist/css/bootstrap.css   (ca22a1cb)
2018-05-08T22:53:40.6628227+02:00 0HLDL4N066855:00000001 [INF] Executed action "Inventory.Web.Controllers.HomeController.Index (Inventory.Web)" in 9183.7885ms (afa2e885)
2018-05-08T22:53:40.6853493+02:00 0HLDL4N066857:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:51686/css/site.css   (ca22a1cb)
2018-05-08T22:53:40.7492987+02:00 0HLDL4N066858:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:51686/lib/jquery/dist/jquery.js   (ca22a1cb)
2018-05-08T22:53:40.8844002+02:00 0HLDL4N066856:00000001 [INF] Sending file. Request path: '"/lib/bootstrap/dist/css/bootstrap.css"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\lib\bootstrap\dist\css\bootstrap.css"' (27b0a520)
2018-05-08T22:53:40.8942240+02:00 0HLDL4N066858:00000001 [INF] Sending file. Request path: '"/lib/jquery/dist/jquery.js"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\lib\jquery\dist\jquery.js"' (27b0a520)
2018-05-08T22:53:40.9082144+02:00 0HLDL4N066857:00000001 [INF] Sending file. Request path: '"/css/site.css"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\css\site.css"' (27b0a520)
2018-05-08T22:53:40.9105318+02:00 0HLDL4N066859:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:51686/lib/bootstrap/dist/js/bootstrap.js   (ca22a1cb)
2018-05-08T22:53:40.9436926+02:00 0HLDL4N066859:00000001 [INF] Sending file. Request path: '"/lib/bootstrap/dist/js/bootstrap.js"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\lib\bootstrap\dist\js\bootstrap.js"' (27b0a520)
2018-05-08T22:53:40.9646324+02:00 0HLDL4N066855:00000001 [INF] Request finished in 10908.5128ms 200 text/html; charset=utf-8 (791a596a)
2018-05-08T22:53:41.1209871+02:00 0HLDL4N066859:00000001 [INF] Request finished in 447.5702ms 200 application/javascript (791a596a)
2018-05-08T22:53:41.2137218+02:00 0HLDL4N066859:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:51686/images/banner1.svg   (ca22a1cb)
2018-05-08T22:53:41.2366968+02:00 0HLDL4N066855:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:51686/images/banner3.svg   (ca22a1cb)
2018-05-08T22:53:41.2566474+02:00 0HLDL4N066856:00000001 [INF] Request finished in 543.9029ms 200 text/css (791a596a)
2018-05-08T22:53:41.2720640+02:00 0HLDL4N06685A:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:51686/js/site.js?v=ji3-IxbEzYWjzzLCGkF1KDjrT2jLbbrSYXw-AhMPNIA   (ca22a1cb)
2018-05-08T22:53:41.3197309+02:00 0HLDL4N066859:00000002 [INF] Sending file. Request path: '"/images/banner1.svg"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\images\banner1.svg"' (27b0a520)
2018-05-08T22:53:41.3679045+02:00 0HLDL4N066855:00000002 [INF] Sending file. Request path: '"/images/banner3.svg"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\images\banner3.svg"' (27b0a520)
2018-05-08T22:53:41.4441340+02:00 0HLDL4N06685A:00000001 [INF] Sending file. Request path: '"/js/site.js"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\js\site.js"' (27b0a520)
2018-05-08T22:53:41.4865614+02:00 0HLDL4N066856:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:51686/images/banner4.svg   (ca22a1cb)
2018-05-08T22:53:41.5209032+02:00 0HLDL4N066858:00000001 [INF] Request finished in 798.5488ms 200 application/javascript (791a596a)
2018-05-08T22:53:41.5528832+02:00 0HLDL4N066857:00000001 [INF] Request finished in 437.79ms 200 text/css (791a596a)
2018-05-08T22:53:41.6194285+02:00 0HLDL4N066859:00000002 [INF] Request finished in 342.1365ms 200 image/svg+xml (791a596a)
2018-05-08T22:53:41.6236501+02:00 0HLDL4N066856:00000002 [INF] Sending file. Request path: '"/images/banner4.svg"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\images\banner4.svg"' (27b0a520)
2018-05-08T22:53:41.7070547+02:00 0HLDL4N06685A:00000001 [INF] Request finished in 560.2627ms 200 application/javascript (791a596a)
2018-05-08T22:53:41.7467408+02:00 0HLDL4N066856:00000002 [INF] Request finished in 323.2954ms 200 image/svg+xml (791a596a)
2018-05-08T22:53:41.7606688+02:00 0HLDL4N066855:00000002 [INF] Request finished in 235.9638ms 200 image/svg+xml (791a596a)
2018-05-08T22:53:41.7935894+02:00 0HLDL4N066857:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:51686/images/banner2.svg   (ca22a1cb)
2018-05-08T22:53:41.8138811+02:00 0HLDL4N066857:00000002 [INF] Sending file. Request path: '"/images/banner2.svg"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\images\banner2.svg"' (27b0a520)
2018-05-08T22:53:41.8514515+02:00 0HLDL4N066857:00000002 [INF] Request finished in 258.1734ms 200 image/svg+xml (791a596a)
2018-05-08T22:53:41.8896287+02:00 0HLDL4N066858:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:51686/lib/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2   (ca22a1cb)
2018-05-08T22:53:41.9679316+02:00 0HLDL4N066858:00000002 [INF] Sending file. Request path: '"/lib/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\lib\bootstrap\dist\fonts\glyphicons-halflings-regular.woff2"' (27b0a520)
2018-05-08T22:53:42.3539419+02:00 0HLDL4N066859:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:51686/favicon.ico   (ca22a1cb)
2018-05-08T22:53:42.5442519+02:00 0HLDL4N066859:00000003 [INF] Sending file. Request path: '"/favicon.ico"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\favicon.ico"' (27b0a520)
2018-05-08T22:53:42.5517432+02:00 0HLDL4N066858:00000002 [INF] Request finished in 170.0626ms 200 font/woff2 (791a596a)
2018-05-08T22:53:42.5752110+02:00 0HLDL4N066856:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:51686/favicon.ico   (ca22a1cb)
2018-05-08T22:53:42.5919651+02:00 0HLDL4N066859:00000003 [INF] Request finished in 351.4071ms 200 image/x-icon (791a596a)
2018-05-08T22:53:42.6150696+02:00 0HLDL4N066856:00000003 [INF] Sending file. Request path: '"/favicon.ico"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\favicon.ico"' (27b0a520)
2018-05-08T22:53:42.6574035+02:00 0HLDL4N066856:00000003 [INF] Request finished in 414.1139ms 200 image/x-icon (791a596a)
2018-05-08T22:54:08.5040534+02:00 0HLDL4N066856:00000004 [INF] Request starting HTTP/1.1 GET http://localhost:51686/Category/Index   (ca22a1cb)
2018-05-08T22:54:08.5324257+02:00 0HLDL4N066856:00000004 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" in 2.2376ms (afa2e885)
2018-05-08T22:54:08.8589887+02:00 0HLDL4N066856:00000004 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.InvalidOperationException: Unable to resolve service for type 'Inventory.Services.Interfaces.ICategoryService' while attempting to activate 'Inventory.Web.Controllers.CategoryController'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-05-08T22:54:09.5769719+02:00 0HLDL4N066856:00000004 [INF] Request finished in 1049.7452ms 500 text/html; charset=utf-8 (791a596a)
2018-05-08T22:54:17.2115250+02:00 0HLDL4N066856:00000005 [INF] Request starting HTTP/1.1 GET http://localhost:51686/Category/Index   (ca22a1cb)
2018-05-08T22:54:17.2307118+02:00 0HLDL4N066856:00000005 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" in 1.6917ms (afa2e885)
2018-05-08T22:54:17.4690068+02:00 0HLDL4N066856:00000005 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.InvalidOperationException: Unable to resolve service for type 'Inventory.Services.Interfaces.ICategoryService' while attempting to activate 'Inventory.Web.Controllers.CategoryController'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-05-08T22:54:17.8852115+02:00 0HLDL4N066856:00000005 [INF] Request finished in 625.6066ms 500 text/html; charset=utf-8 (791a596a)
2018-05-08T22:54:47.3626941+02:00 0HLDL4N066856:00000006 [INF] Request starting HTTP/1.1 GET http://localhost:51686/Category/Index   (ca22a1cb)
2018-05-08T22:54:47.3865490+02:00 0HLDL4N066856:00000006 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" in 5.6443ms (afa2e885)
2018-05-08T22:54:47.6261034+02:00 0HLDL4N066856:00000006 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.InvalidOperationException: Unable to resolve service for type 'Inventory.Services.Interfaces.ICategoryService' while attempting to activate 'Inventory.Web.Controllers.CategoryController'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-05-08T22:54:48.1346839+02:00 0HLDL4N066856:00000006 [INF] Request finished in 723.481ms 500 text/html; charset=utf-8 (791a596a)
2018-05-08T22:54:49.2370800+02:00 0HLDL4N066856:00000007 [INF] Request starting HTTP/1.1 GET http://localhost:51686/Category/Index   (ca22a1cb)
2018-05-08T22:54:49.2574747+02:00 0HLDL4N066856:00000007 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" in 1.5601ms (afa2e885)
2018-05-08T22:54:49.6618820+02:00 0HLDL4N066856:00000007 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.InvalidOperationException: Unable to resolve service for type 'Inventory.Services.Interfaces.ICategoryService' while attempting to activate 'Inventory.Web.Controllers.CategoryController'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-05-08T22:54:50.0966018+02:00 0HLDL4N066856:00000007 [INF] Request finished in 828.2433ms 500 text/html; charset=utf-8 (791a596a)
2018-05-08T23:01:24.6270154+02:00 0HLDL4RDP8RVI:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/   (ca22a1cb)
2018-05-08T23:01:25.2499233+02:00 0HLDL4RDP8RVJ:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/Category/Index   (ca22a1cb)
2018-05-08T23:01:26.1222119+02:00 0HLDL4RDP8RVI:00000001 [INF] Executing action method "Inventory.Web.Controllers.HomeController.Index (Inventory.Web)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-05-08T23:01:26.1202565+02:00 0HLDL4RDP8RVJ:00000001 [INF] Executing action method "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-05-08T23:03:10.2496171+02:00 0HLDL4SD9L43F:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/Category/Index   (ca22a1cb)
2018-05-08T23:03:10.2496172+02:00 0HLDL4SD9L43H:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/   (ca22a1cb)
2018-05-08T23:03:11.7993911+02:00 0HLDL4SD9L43F:00000001 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" in 46.8079ms (afa2e885)
2018-05-08T23:03:11.9168974+02:00 0HLDL4SD9L43H:00000001 [INF] Executing action method "Inventory.Web.Controllers.HomeController.Index (Inventory.Web)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-05-08T23:03:12.2482148+02:00 0HLDL4SD9L43F:00000001 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.InvalidOperationException: Unable to resolve service for type 'Inventory.Services.Interfaces.ICategoryService' while attempting to activate 'Inventory.Web.Controllers.CategoryController'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-05-08T23:03:13.3643880+02:00 0HLDL4SD9L43F:00000001 [INF] Request finished in 3139.9078ms 500 text/html; charset=utf-8 (791a596a)
2018-05-08T23:03:18.1205223+02:00 0HLDL4SD9L43H:00000001 [INF] Executing ViewResult, running view at path "/Views/Home/Index.cshtml". (9707eebe)
2018-05-08T23:03:19.5344180+02:00 0HLDL4SD9L43H:00000001 [INF] Executed action "Inventory.Web.Controllers.HomeController.Index (Inventory.Web)" in 7800.3707ms (afa2e885)
2018-05-08T23:03:19.5534628+02:00 0HLDL4SD9L43H:00000001 [INF] Committing the session was canceled. (12038ba6)
2018-05-08T23:03:19.5680239+02:00 0HLDL4SD9L43H:00000001 [INF] Request finished in 9452.3175ms 200 text/html; charset=utf-8 (791a596a)
2018-05-08T23:25:48.1282215+02:00 0HLDL591TGH7A:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/Category/Index   (ca22a1cb)
2018-05-08T23:25:48.1282215+02:00 0HLDL591TGH7B:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/   (ca22a1cb)
2018-05-08T23:25:49.7280672+02:00 0HLDL591TGH7A:00000001 [INF] Executing action method "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-05-08T23:25:49.7275633+02:00 0HLDL591TGH7B:00000001 [INF] Executing action method "Inventory.Web.Controllers.HomeController.Index (Inventory.Web)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-05-08T23:26:19.5235407+02:00 0HLDL591TGH7A:00000001 [INF] Executing ViewResult, running view at path "/Views/Category/Index.cshtml". (9707eebe)
2018-05-08T23:26:19.5332711+02:00 0HLDL591TGH7B:00000001 [INF] Executing ViewResult, running view at path "/Views/Home/Index.cshtml". (9707eebe)
2018-05-08T23:26:21.3858948+02:00 0HLDL591TGH7B:00000001 [INF] Executed action "Inventory.Web.Controllers.HomeController.Index (Inventory.Web)" in 31711.7607ms (afa2e885)
2018-05-08T23:26:21.6137955+02:00 0HLDL591TGH7A:00000001 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" in 31711.391ms (afa2e885)
2018-05-08T23:26:21.8090772+02:00 0HLDL591TGH7A:00000001 [INF] Request finished in 33712.5462ms 200 text/html; charset=utf-8 (791a596a)
2018-05-08T23:26:21.8288399+02:00 0HLDL591TGH7B:00000001 [INF] Request finished in 33712.6221ms 200 text/html; charset=utf-8 (791a596a)
2018-05-08T23:28:29.3512405+02:00 0HLDL5AHVUSBP:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/Category/Index   (ca22a1cb)
2018-05-08T23:28:30.9586019+02:00 0HLDL5AHVUSBP:00000001 [INF] Executing action method "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-05-08T23:28:45.4236845+02:00 0HLDL5AHVUSBP:00000001 [INF] Executing ViewResult, running view at path "/Views/Category/Index.cshtml". (9707eebe)
2018-05-08T23:28:48.1891244+02:00 0HLDL5AHVUSBP:00000001 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" in 17219.9249ms (afa2e885)
2018-05-08T23:28:48.1930142+02:00 0HLDL5AHVUSBR:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/bootstrap/dist/css/bootstrap.css   (ca22a1cb)
2018-05-08T23:28:48.2231406+02:00 0HLDL5AHVUSBT:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/js/site.js?v=ji3-IxbEzYWjzzLCGkF1KDjrT2jLbbrSYXw-AhMPNIA   (ca22a1cb)
2018-05-08T23:28:48.2353514+02:00 0HLDL5AHVUSBU:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/css/site.css   (ca22a1cb)
2018-05-08T23:28:48.2418549+02:00 0HLDL5AHVUSBS:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/jquery/dist/jquery.js   (ca22a1cb)
2018-05-08T23:28:48.3088309+02:00 0HLDL5AHVUSBR:00000001 [INF] The file "/lib/bootstrap/dist/css/bootstrap.css" was not modified (f1f8d725)
2018-05-08T23:28:48.4136707+02:00 0HLDL5AHVUSBT:00000001 [INF] The file "/js/site.js" was not modified (f1f8d725)
2018-05-08T23:28:48.4357891+02:00 0HLDL5AHVUSBU:00000001 [INF] The file "/css/site.css" was not modified (f1f8d725)
2018-05-08T23:28:48.4495186+02:00 0HLDL5AHVUSBS:00000001 [INF] The file "/lib/jquery/dist/jquery.js" was not modified (f1f8d725)
2018-05-08T23:28:48.6014497+02:00 0HLDL5AHVUSBU:00000001 [INF] Request finished in 265.4968ms 304 text/css (791a596a)
2018-05-08T23:28:48.6091995+02:00 0HLDL5AHVUSBS:00000001 [INF] Request finished in 312.9773ms 304 application/javascript (791a596a)
2018-05-08T23:28:48.6131347+02:00 0HLDL5AHVUSBT:00000001 [INF] Request finished in 255.6052ms 304 application/javascript (791a596a)
2018-05-08T23:28:48.6218830+02:00 0HLDL5AHVUSBP:00000001 [INF] Request finished in 19118.3521ms 200 text/html; charset=utf-8 (791a596a)
2018-05-08T23:28:48.6379825+02:00 0HLDL5AHVUSBR:00000001 [INF] Request finished in 231.8417ms 304 text/css (791a596a)
2018-05-08T23:28:48.6966229+02:00 0HLDL5AHVUSBV:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/bootstrap/dist/js/bootstrap.js   (ca22a1cb)
2018-05-08T23:28:48.7133549+02:00 0HLDL5AHVUSBV:00000001 [INF] The file "/lib/bootstrap/dist/js/bootstrap.js" was not modified (f1f8d725)
2018-05-08T23:28:48.8143149+02:00 0HLDL5AHVUSBV:00000001 [INF] Request finished in 50.54ms 304 application/javascript (791a596a)
2018-05-08T23:28:53.3481890+02:00 0HLDL5AHVUSBP:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44391/Category/Index   (ca22a1cb)
2018-05-08T23:28:53.3702448+02:00 0HLDL5AHVUSBP:00000002 [INF] Executing action method "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-05-08T23:28:53.4460428+02:00 0HLDL5AHVUSBP:00000002 [INF] Executing ViewResult, running view at path "/Views/Category/Index.cshtml". (9707eebe)
2018-05-08T23:28:53.5811972+02:00 0HLDL5AHVUSBP:00000002 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" in 107.3938ms (afa2e885)
2018-05-08T23:28:53.6242526+02:00 0HLDL5AHVUSBR:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/bootstrap/dist/css/bootstrap.css   (ca22a1cb)
2018-05-08T23:28:53.6951186+02:00 0HLDL5AHVUSBT:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44391/css/site.css   (ca22a1cb)
2018-05-08T23:28:53.7043495+02:00 0HLDL5AHVUSBS:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44391/js/site.js?v=ji3-IxbEzYWjzzLCGkF1KDjrT2jLbbrSYXw-AhMPNIA   (ca22a1cb)
2018-05-08T23:28:53.7130325+02:00 0HLDL5AHVUSBP:00000002 [INF] Request finished in 250.0704ms 200 text/html; charset=utf-8 (791a596a)
2018-05-08T23:28:53.7362063+02:00 0HLDL5AHVUSBR:00000002 [INF] The file "/lib/bootstrap/dist/css/bootstrap.css" was not modified (f1f8d725)
2018-05-08T23:28:53.7824989+02:00 0HLDL5AHVUSBS:00000002 [INF] The file "/js/site.js" was not modified (f1f8d725)
2018-05-08T23:28:53.8026875+02:00 0HLDL5AHVUSBU:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/jquery/dist/jquery.js   (ca22a1cb)
2018-05-08T23:28:53.8199785+02:00 0HLDL5AHVUSBT:00000002 [INF] The file "/css/site.css" was not modified (f1f8d725)
2018-05-08T23:28:53.8371952+02:00 0HLDL5AHVUSBR:00000002 [INF] Request finished in 172.1803ms 304 text/css (791a596a)
2018-05-08T23:28:53.8932346+02:00 0HLDL5AHVUSBS:00000002 [INF] Request finished in 174.2247ms 304 application/javascript (791a596a)
2018-05-08T23:28:53.9243000+02:00 0HLDL5AHVUSBT:00000002 [INF] Request finished in 234.5235ms 304 text/css (791a596a)
2018-05-08T23:28:53.9435535+02:00 0HLDL5AHVUSBU:00000002 [INF] The file "/lib/jquery/dist/jquery.js" was not modified (f1f8d725)
2018-05-08T23:28:53.9699280+02:00 0HLDL5AHVUSBV:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/bootstrap/dist/js/bootstrap.js   (ca22a1cb)
2018-05-08T23:28:54.0368720+02:00 0HLDL5AHVUSBV:00000002 [INF] The file "/lib/bootstrap/dist/js/bootstrap.js" was not modified (f1f8d725)
2018-05-08T23:28:54.1817324+02:00 0HLDL5AHVUSBU:00000002 [INF] Request finished in 218.4676ms 304 application/javascript (791a596a)
2018-05-08T23:28:54.1991675+02:00 0HLDL5AHVUSBV:00000002 [INF] Request finished in 149.6089ms 304 application/javascript (791a596a)
