2018-04-04T10:37:00.3968184+02:00 0HLCQ0STT8UME:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/   (ca22a1cb)
2018-04-04T10:37:01.0638501+02:00 0HLCQ0STT8UME:00000001 [INF] Executing action method "Inventory.Web.Controllers.HomeController.Index (Inventory.Web)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-04-04T10:37:06.9303015+02:00 0HLCQ0STT8UME:00000001 [INF] Executing ViewResult, running view at path "/Views/Home/Index.cshtml". (9707eebe)
2018-04-04T10:37:08.1364252+02:00 0HLCQ0STT8UME:00000001 [INF] Executed action "Inventory.Web.Controllers.HomeController.Index (Inventory.Web)" in 7044.4448ms (afa2e885)
2018-04-04T10:37:08.1799464+02:00 0HLCQ0STT8UME:00000001 [INF] Request finished in 7802.7606ms 200 text/html; charset=utf-8 (791a596a)
2018-04-04T10:37:08.3123647+02:00 0HLCQ0STT8UMI:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/images/banner2.svg   (ca22a1cb)
2018-04-04T10:37:08.3414151+02:00 0HLCQ0STT8UMH:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/images/banner4.svg   (ca22a1cb)
2018-04-04T10:37:08.3448904+02:00 0HLCQ0STT8UME:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/bootstrap/dist/css/bootstrap.css   (ca22a1cb)
2018-04-04T10:37:08.3637698+02:00 0HLCQ0STT8UMF:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/css/site.css   (ca22a1cb)
2018-04-04T10:37:08.4036261+02:00 0HLCQ0STT8UMH:00000001 [INF] Sending file. Request path: '"/images/banner4.svg"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\images\banner4.svg"' (27b0a520)
2018-04-04T10:37:08.4282115+02:00 0HLCQ0STT8UMI:00000001 [INF] Sending file. Request path: '"/images/banner2.svg"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\images\banner2.svg"' (27b0a520)
2018-04-04T10:37:08.4329933+02:00 0HLCQ0STT8UME:00000002 [INF] Sending file. Request path: '"/lib/bootstrap/dist/css/bootstrap.css"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\lib\bootstrap\dist\css\bootstrap.css"' (27b0a520)
2018-04-04T10:37:08.4424181+02:00 0HLCQ0STT8UMF:00000001 [INF] Sending file. Request path: '"/css/site.css"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\css\site.css"' (27b0a520)
2018-04-04T10:37:08.4498621+02:00 0HLCQ0STT8UMG:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/images/banner3.svg   (ca22a1cb)
2018-04-04T10:37:08.4910436+02:00 0HLCQ0STT8UMF:00000001 [INF] Request finished in 187.0796ms 200 text/css (791a596a)
2018-04-04T10:37:08.5707803+02:00 0HLCQ0STT8UMH:00000001 [INF] Request finished in 233.9113ms 200 image/svg+xml (791a596a)
2018-04-04T10:37:08.5858253+02:00 0HLCQ0STT8UMG:00000001 [INF] Sending file. Request path: '"/images/banner3.svg"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\images\banner3.svg"' (27b0a520)
2018-04-04T10:37:08.6534843+02:00 0HLCQ0STT8UMM:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/bootstrap/dist/js/bootstrap.js   (ca22a1cb)
2018-04-04T10:37:08.6589916+02:00 0HLCQ0STT8UMJ:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/js/site.js?v=ji3-IxbEzYWjzzLCGkF1KDjrT2jLbbrSYXw-AhMPNIA   (ca22a1cb)
2018-04-04T10:37:08.6691514+02:00 0HLCQ0STT8UMI:00000001 [INF] Request finished in 226.2513ms 200 image/svg+xml (791a596a)
2018-04-04T10:37:08.6715561+02:00 0HLCQ0STT8UMK:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/jquery/dist/jquery.js   (ca22a1cb)
2018-04-04T10:37:08.6756708+02:00 0HLCQ0STT8UML:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/images/banner1.svg   (ca22a1cb)
2018-04-04T10:37:08.7351388+02:00 0HLCQ0STT8UMK:00000001 [INF] Sending file. Request path: '"/lib/jquery/dist/jquery.js"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\lib\jquery\dist\jquery.js"' (27b0a520)
2018-04-04T10:37:08.7580076+02:00 0HLCQ0STT8UML:00000001 [INF] Sending file. Request path: '"/images/banner1.svg"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\images\banner1.svg"' (27b0a520)
2018-04-04T10:37:08.7933400+02:00 0HLCQ0STT8UMJ:00000001 [INF] Sending file. Request path: '"/js/site.js"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\js\site.js"' (27b0a520)
2018-04-04T10:37:08.8318861+02:00 0HLCQ0STT8UML:00000001 [INF] Request finished in 177.0131ms 200 image/svg+xml (791a596a)
2018-04-04T10:37:08.8393636+02:00 0HLCQ0STT8UMM:00000001 [INF] Sending file. Request path: '"/lib/bootstrap/dist/js/bootstrap.js"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\lib\bootstrap\dist\js\bootstrap.js"' (27b0a520)
2018-04-04T10:37:08.8641784+02:00 0HLCQ0STT8UMG:00000001 [INF] Request finished in 485.147ms 200 image/svg+xml (791a596a)
2018-04-04T10:37:08.9898261+02:00 0HLCQ0STT8UMJ:00000001 [INF] Request finished in 235.557ms 200 application/javascript (791a596a)
2018-04-04T10:37:09.0438011+02:00 0HLCQ0STT8UMK:00000001 [INF] Request finished in 331.0147ms 200 application/javascript (791a596a)
2018-04-04T10:37:09.0633838+02:00 0HLCQ0STT8UMF:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2   (ca22a1cb)
2018-04-04T10:37:09.0877876+02:00 0HLCQ0STT8UME:00000002 [INF] Request finished in 566.1612ms 200 text/css (791a596a)
2018-04-04T10:37:09.0917541+02:00 0HLCQ0STT8UMM:00000001 [INF] Request finished in 407.4943ms 200 application/javascript (791a596a)
2018-04-04T10:37:09.1349857+02:00 0HLCQ0STT8UMF:00000002 [INF] Sending file. Request path: '"/lib/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\lib\bootstrap\dist\fonts\glyphicons-halflings-regular.woff2"' (27b0a520)
2018-04-04T10:37:09.1941436+02:00 0HLCQ0STT8UMF:00000002 [INF] Request finished in 226.0037ms 200 font/woff2 (791a596a)
2018-04-04T10:37:09.2575053+02:00 0HLCQ0STT8UMI:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44391/favicon.ico   (ca22a1cb)
2018-04-04T10:37:09.2718476+02:00 0HLCQ0STT8UMI:00000002 [INF] Sending file. Request path: '"/favicon.ico"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\favicon.ico"' (27b0a520)
2018-04-04T10:37:09.3008833+02:00 0HLCQ0STT8UMI:00000002 [INF] Request finished in 35.8045ms 200 image/x-icon (791a596a)
2018-04-04T10:37:12.4261076+02:00 0HLCQ0STT8UMH:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44391/Home/About   (ca22a1cb)
2018-04-04T10:37:12.4459009+02:00 0HLCQ0STT8UMH:00000002 [INF] Executing action method "Inventory.Web.Controllers.HomeController.About (Inventory.Web)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-04-04T10:37:12.6762996+02:00 0HLCQ0STT8UMH:00000002 [INF] Executing ViewResult, running view at path "/Views/Home/About.cshtml". (9707eebe)
2018-04-04T10:37:12.7404400+02:00 0HLCQ0STT8UMH:00000002 [INF] Executed action "Inventory.Web.Controllers.HomeController.About (Inventory.Web)" in 258.1259ms (afa2e885)
2018-04-04T10:37:12.7608121+02:00 0HLCQ0STT8UMH:00000002 [INF] Request finished in 328.7867ms 200 text/html; charset=utf-8 (791a596a)
2018-04-04T11:21:21.3073889+02:00 0HLCQ1LMSU3FA:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/   (ca22a1cb)
2018-04-04T11:21:21.8785599+02:00 0HLCQ1LMSU3FA:00000001 [INF] Executing action method "Inventory.Web.Controllers.HomeController.Index (Inventory.Web)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-04-04T11:21:26.3429202+02:00 0HLCQ1LMSU3FA:00000001 [INF] Executing ViewResult, running view at path "/Views/Home/Index.cshtml". (9707eebe)
2018-04-04T11:21:27.3868961+02:00 0HLCQ1LMSU3FA:00000001 [INF] Executed action "Inventory.Web.Controllers.HomeController.Index (Inventory.Web)" in 5513.1947ms (afa2e885)
2018-04-04T11:21:27.5377290+02:00 0HLCQ1LMSU3FC:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/bootstrap/dist/css/bootstrap.css   (ca22a1cb)
2018-04-04T11:21:27.5474653+02:00 0HLCQ1LMSU3FA:00000001 [INF] Request finished in 6180.7106ms 200 text/html; charset=utf-8 (791a596a)
2018-04-04T11:21:27.5642693+02:00 0HLCQ1LMSU3FF:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/bootstrap/dist/js/bootstrap.js   (ca22a1cb)
2018-04-04T11:21:27.5749427+02:00 0HLCQ1LMSU3FD:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/jquery/dist/jquery.js   (ca22a1cb)
2018-04-04T11:21:27.6062243+02:00 0HLCQ1LMSU3FF:00000001 [INF] The file "/lib/bootstrap/dist/js/bootstrap.js" was not modified (f1f8d725)
2018-04-04T11:21:27.6256084+02:00 0HLCQ1LMSU3FD:00000001 [INF] The file "/lib/jquery/dist/jquery.js" was not modified (f1f8d725)
2018-04-04T11:21:27.6469136+02:00 0HLCQ1LMSU3FC:00000001 [INF] Sending file. Request path: '"/lib/bootstrap/dist/css/bootstrap.css"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\lib\bootstrap\dist\css\bootstrap.css"' (27b0a520)
2018-04-04T11:21:27.7064771+02:00 0HLCQ1LMSU3FF:00000001 [INF] Request finished in 93.8494ms 304 application/javascript (791a596a)
2018-04-04T11:21:27.7509112+02:00 0HLCQ1LMSU3FD:00000001 [INF] Request finished in 102.3215ms 304 application/javascript (791a596a)
2018-04-04T11:21:27.7847693+02:00 0HLCQ1LMSU3FA:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44391/css/site.css   (ca22a1cb)
2018-04-04T11:21:27.8639637+02:00 0HLCQ1LMSU3FE:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/js/site.js?v=ji3-IxbEzYWjzzLCGkF1KDjrT2jLbbrSYXw-AhMPNIA   (ca22a1cb)
2018-04-04T11:21:27.9238856+02:00 0HLCQ1LMSU3FA:00000002 [INF] Sending file. Request path: '"/css/site.css"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\css\site.css"' (27b0a520)
2018-04-04T11:21:27.9431154+02:00 0HLCQ1LMSU3FE:00000001 [INF] The file "/js/site.js" was not modified (f1f8d725)
2018-04-04T11:21:27.9711041+02:00 0HLCQ1LMSU3FC:00000001 [INF] Request finished in 378.1882ms 200 text/css (791a596a)
2018-04-04T11:21:28.0506011+02:00 0HLCQ1LMSU3FA:00000002 [INF] Request finished in 250.7163ms 200 text/css (791a596a)
2018-04-04T11:21:28.0699594+02:00 0HLCQ1LMSU3FE:00000001 [INF] Request finished in 165.5151ms 304 application/javascript (791a596a)
2018-04-04T11:21:38.9882081+02:00 0HLCQ1LMSU3FF:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44391/category/index   (ca22a1cb)
2018-04-04T11:21:39.0035584+02:00 0HLCQ1LMSU3FF:00000002 [INF] Executing action method "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-04-04T11:21:39.0258430+02:00 0HLCQ1LMSU3FF:00000002 [ERR] The view '"Index"' was not found. Searched locations: ["/Views/Category/Index.cshtml", "/Views/Shared/Index.cshtml"] (9bb2756c)
2018-04-04T11:21:39.0444543+02:00 0HLCQ1LMSU3FF:00000002 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" in 38.7888ms (afa2e885)
2018-04-04T11:21:39.2498539+02:00 0HLCQ1LMSU3FF:00000002 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.InvalidOperationException: The view 'Index' was not found. The following locations were searched:
/Views/Category/Index.cshtml
/Views/Shared/Index.cshtml
   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-04-04T11:21:39.4971087+02:00 0HLCQ1LMSU3FF:00000002 [INF] Request finished in 469.7963ms 500 text/html; charset=utf-8 (791a596a)
2018-04-04T11:23:39.6396115+02:00 0HLCQ1N03CFDV:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/   (ca22a1cb)
2018-04-04T11:23:40.2801497+02:00 0HLCQ1N03CFDV:00000001 [INF] Executing action method "Inventory.Web.Controllers.HomeController.Index (Inventory.Web)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-04-04T11:23:44.5664323+02:00 0HLCQ1N03CFDV:00000001 [INF] Executing ViewResult, running view at path "/Views/Home/Index.cshtml". (9707eebe)
2018-04-04T11:23:44.8876495+02:00 0HLCQ1N03CFE1:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/category/create   (ca22a1cb)
2018-04-04T11:23:44.9193291+02:00 0HLCQ1N03CFE1:00000001 [INF] Executing action method "Inventory.Web.Controllers.CategoryController.Create (Inventory.Web)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-04-04T11:23:45.9119958+02:00 0HLCQ1N03CFE1:00000001 [INF] Executing ViewResult, running view at path "/Views/Category/Create.cshtml". (9707eebe)
2018-04-04T11:23:46.0317181+02:00 0HLCQ1N03CFDV:00000001 [INF] Executed action "Inventory.Web.Controllers.HomeController.Index (Inventory.Web)" in 5743.0574ms (afa2e885)
2018-04-04T11:23:46.0649536+02:00 0HLCQ1N03CFDV:00000001 [INF] Committing the session was canceled. (12038ba6)
2018-04-04T11:23:46.0951062+02:00 0HLCQ1N03CFDV:00000001 [INF] Request finished in 6595.4075ms 200 text/html; charset=utf-8 (791a596a)
2018-04-04T11:23:46.5293511+02:00 0HLCQ1N03CFE1:00000001 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Create (Inventory.Web)" in 1586.5378ms (afa2e885)
2018-04-04T11:23:46.6428878+02:00 0HLCQ1N03CFE1:00000001 [INF] Request finished in 1662.7688ms 200 text/html; charset=utf-8 (791a596a)
2018-04-04T11:23:46.7596199+02:00 0HLCQ1N03CFE1:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/jquery-validation/dist/jquery.validate.js   (ca22a1cb)
2018-04-04T11:23:46.7957224+02:00 0HLCQ1N03CFE2:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js   (ca22a1cb)
2018-04-04T11:23:46.8211963+02:00 0HLCQ1N03CFE2:00000001 [INF] Sending file. Request path: '"/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\lib\jquery-validation-unobtrusive\jquery.validate.unobtrusive.js"' (27b0a520)
2018-04-04T11:23:46.8482712+02:00 0HLCQ1N03CFE1:00000002 [INF] Sending file. Request path: '"/lib/jquery-validation/dist/jquery.validate.js"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\lib\jquery-validation\dist\jquery.validate.js"' (27b0a520)
2018-04-04T11:23:46.9848796+02:00 0HLCQ1N03CFE2:00000001 [INF] Request finished in 261.93ms 200 application/javascript (791a596a)
2018-04-04T11:23:47.0039604+02:00 0HLCQ1N03CFE1:00000002 [INF] Request finished in 195.1487ms 200 application/javascript (791a596a)
2018-04-04T11:25:03.4361477+02:00 0HLCQ1N03CFE3:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/category/create   (ca22a1cb)
2018-04-04T11:25:03.4493869+02:00 0HLCQ1N03CFE3:00000001 [INF] Executing action method "Inventory.Web.Controllers.CategoryController.Create (Inventory.Web)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-04-04T11:25:03.4634243+02:00 0HLCQ1N03CFE3:00000001 [INF] Executing ViewResult, running view at path "/Views/Category/Create.cshtml". (9707eebe)
2018-04-04T11:25:03.6440805+02:00 0HLCQ1N03CFE3:00000001 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Create (Inventory.Web)" in 48.04ms (afa2e885)
2018-04-04T11:25:03.7631754+02:00 0HLCQ1N03CFE7:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/js/site.js?v=ji3-IxbEzYWjzzLCGkF1KDjrT2jLbbrSYXw-AhMPNIA   (ca22a1cb)
2018-04-04T11:25:03.8152083+02:00 0HLCQ1N03CFE6:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js   (ca22a1cb)
2018-04-04T11:25:03.8282038+02:00 0HLCQ1N03CFE3:00000001 [INF] Request finished in 222.1291ms 200 text/html; charset=utf-8 (791a596a)
2018-04-04T11:25:03.8391516+02:00 0HLCQ1N03CFE8:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/css/site.css   (ca22a1cb)
2018-04-04T11:25:03.8806786+02:00 0HLCQ1N03CFEA:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/jquery-validation/dist/jquery.validate.js   (ca22a1cb)
2018-04-04T11:25:03.9000716+02:00 0HLCQ1N03CFE7:00000001 [INF] The file "/js/site.js" was not modified (f1f8d725)
2018-04-04T11:25:03.9391354+02:00 0HLCQ1N03CFE6:00000001 [INF] The file "/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js" was not modified (f1f8d725)
2018-04-04T11:25:03.9591104+02:00 0HLCQ1N03CFE8:00000001 [INF] The file "/css/site.css" was not modified (f1f8d725)
2018-04-04T11:25:03.9996199+02:00 0HLCQ1N03CFE5:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/jquery/dist/jquery.js   (ca22a1cb)
2018-04-04T11:25:04.0073602+02:00 0HLCQ1N03CFEA:00000001 [INF] The file "/lib/jquery-validation/dist/jquery.validate.js" was not modified (f1f8d725)
2018-04-04T11:25:04.0622500+02:00 0HLCQ1N03CFE9:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/bootstrap/dist/js/bootstrap.js   (ca22a1cb)
2018-04-04T11:25:04.0669354+02:00 0HLCQ1N03CFE7:00000001 [INF] Request finished in 264.0134ms 304 application/javascript (791a596a)
2018-04-04T11:25:04.0922285+02:00 0HLCQ1N03CFE6:00000001 [INF] Request finished in 297.593ms 304 application/javascript (791a596a)
2018-04-04T11:25:04.0962048+02:00 0HLCQ1N03CFE8:00000001 [INF] Request finished in 272.4788ms 304 text/css (791a596a)
2018-04-04T11:25:04.1100941+02:00 0HLCQ1N03CFEA:00000001 [INF] Request finished in 260.656ms 304 application/javascript (791a596a)
2018-04-04T11:25:04.1235047+02:00 0HLCQ1N03CFE4:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/bootstrap/dist/css/bootstrap.css   (ca22a1cb)
2018-04-04T11:25:04.1452685+02:00 0HLCQ1N03CFE9:00000001 [INF] The file "/lib/bootstrap/dist/js/bootstrap.js" was not modified (f1f8d725)
2018-04-04T11:25:04.1530137+02:00 0HLCQ1N03CFE5:00000001 [INF] The file "/lib/jquery/dist/jquery.js" was not modified (f1f8d725)
2018-04-04T11:25:04.1762641+02:00 0HLCQ1N03CFE9:00000001 [INF] Request finished in 433.4286ms 304 application/javascript (791a596a)
2018-04-04T11:25:04.1935300+02:00 0HLCQ1N03CFE4:00000001 [INF] The file "/lib/bootstrap/dist/css/bootstrap.css" was not modified (f1f8d725)
2018-04-04T11:25:04.2115032+02:00 0HLCQ1N03CFE5:00000001 [INF] Request finished in 511.7034ms 304 application/javascript (791a596a)
2018-04-04T11:25:04.2159160+02:00 0HLCQ1N03CFE4:00000001 [INF] Request finished in 555.7426ms 304 text/css (791a596a)
2018-04-04T11:25:09.4913894+02:00 0HLCQ1N03CFE3:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44391/category/create   (ca22a1cb)
2018-04-04T11:25:09.5049570+02:00 0HLCQ1N03CFE3:00000002 [INF] Executing action method "Inventory.Web.Controllers.CategoryController.Create (Inventory.Web)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-04-04T11:25:09.8696629+02:00 0HLCQ1N03CFE3:00000002 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Create (Inventory.Web)" in 368.2373ms (afa2e885)
2018-04-04T11:25:10.1171829+02:00 0HLCQ1N03CFE3:00000002 [ERR] An unhandled exception has occurred while executing the request (cf926119)
Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException: One or more compilation failures occurred:
C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\Views\Category\Create.cshtml(33,155): error CS1003: Syntax error, ',' expected
C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\Views\Category\Create.cshtml(33,165): error CS1003: Syntax error, ',' expected
C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\Views\Category\Create.cshtml(33,155): error CS0103: The name 'Warehouse' does not exist in the current context
C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\Views\Category\Create.cshtml(33,165): error CS0103: The name 'Place' does not exist in the current context
C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\Views\Category\Create.cshtml(33,147): error CS1061: 'Category' does not contain a definition for 'Default' and no extension method 'Default' accepting a first argument of type 'Category' could be found (are you missing a using directive or an assembly reference?)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(RazorCodeDocument codeDocument, String generatedCode)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CreateCacheEntry(String normalizedPath)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-04-04T11:25:10.3731616+02:00 0HLCQ1N03CFE3:00000002 [INF] Request finished in 808.2095ms 500 text/html; charset=utf-8 (791a596a)
2018-04-04T11:26:19.0964306+02:00 0HLCQ1N03CFEB:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/category/create   (ca22a1cb)
2018-04-04T11:26:19.1070459+02:00 0HLCQ1N03CFEB:00000001 [INF] Executing action method "Inventory.Web.Controllers.CategoryController.Create (Inventory.Web)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-04-04T11:26:19.7913789+02:00 0HLCQ1N03CFEB:00000001 [INF] Executing ViewResult, running view at path "/Views/Category/Create.cshtml". (9707eebe)
2018-04-04T11:26:19.8694398+02:00 0HLCQ1N03CFEB:00000001 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Create (Inventory.Web)" in 752.3287ms (afa2e885)
2018-04-04T11:26:19.8979570+02:00 0HLCQ1N03CFEB:00000001 [INF] Request finished in 784.8418ms 200 text/html; charset=utf-8 (791a596a)
2018-04-04T11:26:20.0241143+02:00 0HLCQ1N03CFEB:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/bootstrap/dist/css/bootstrap.css   (ca22a1cb)
2018-04-04T11:26:20.0443271+02:00 0HLCQ1N03CFED:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/js/site.js?v=ji3-IxbEzYWjzzLCGkF1KDjrT2jLbbrSYXw-AhMPNIA   (ca22a1cb)
2018-04-04T11:26:20.0529710+02:00 0HLCQ1N03CFEF:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js   (ca22a1cb)
2018-04-04T11:26:20.0580210+02:00 0HLCQ1N03CFEC:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/jquery/dist/jquery.js   (ca22a1cb)
2018-04-04T11:26:20.0623075+02:00 0HLCQ1N03CFEG:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/bootstrap/dist/js/bootstrap.js   (ca22a1cb)
2018-04-04T11:26:20.0678720+02:00 0HLCQ1N03CFEH:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/jquery-validation/dist/jquery.validate.js   (ca22a1cb)
2018-04-04T11:26:20.1063592+02:00 0HLCQ1N03CFEB:00000002 [INF] The file "/lib/bootstrap/dist/css/bootstrap.css" was not modified (f1f8d725)
2018-04-04T11:26:20.1387353+02:00 0HLCQ1N03CFEE:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/css/site.css   (ca22a1cb)
2018-04-04T11:26:20.1421137+02:00 0HLCQ1N03CFED:00000001 [INF] The file "/js/site.js" was not modified (f1f8d725)
2018-04-04T11:26:20.1609838+02:00 0HLCQ1N03CFEG:00000001 [INF] The file "/lib/bootstrap/dist/js/bootstrap.js" was not modified (f1f8d725)
2018-04-04T11:26:20.1800428+02:00 0HLCQ1N03CFEF:00000001 [INF] The file "/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js" was not modified (f1f8d725)
2018-04-04T11:26:20.2400230+02:00 0HLCQ1N03CFEH:00000001 [INF] The file "/lib/jquery-validation/dist/jquery.validate.js" was not modified (f1f8d725)
2018-04-04T11:26:20.2486228+02:00 0HLCQ1N03CFEB:00000002 [INF] Request finished in 169.1885ms 304 text/css (791a596a)
2018-04-04T11:26:20.2708163+02:00 0HLCQ1N03CFED:00000001 [INF] Request finished in 187.7025ms 304 application/javascript (791a596a)
2018-04-04T11:26:20.2929011+02:00 0HLCQ1N03CFEG:00000001 [INF] Request finished in 186.7904ms 304 application/javascript (791a596a)
2018-04-04T11:26:20.3018427+02:00 0HLCQ1N03CFEC:00000001 [INF] The file "/lib/jquery/dist/jquery.js" was not modified (f1f8d725)
2018-04-04T11:26:20.3195762+02:00 0HLCQ1N03CFEF:00000001 [INF] Request finished in 222.5583ms 304 application/javascript (791a596a)
2018-04-04T11:26:20.3473321+02:00 0HLCQ1N03CFEH:00000001 [INF] Request finished in 265.8122ms 304 application/javascript (791a596a)
2018-04-04T11:26:20.3606904+02:00 0HLCQ1N03CFEE:00000001 [INF] The file "/css/site.css" was not modified (f1f8d725)
2018-04-04T11:26:20.4198207+02:00 0HLCQ1N03CFEC:00000001 [INF] Request finished in 349.5399ms 304 application/javascript (791a596a)
2018-04-04T11:26:20.4719004+02:00 0HLCQ1N03CFEE:00000001 [INF] Request finished in 404.0882ms 304 text/css (791a596a)
2018-04-04T11:26:49.1300522+02:00 0HLCQ1N03CFEB:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:44391/category/create   (ca22a1cb)
2018-04-04T11:26:49.1587411+02:00 0HLCQ1N03CFEB:00000003 [INF] Executing action method "Inventory.Web.Controllers.CategoryController.Create (Inventory.Web)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-04-04T11:26:49.4693283+02:00 0HLCQ1N03CFEB:00000003 [INF] Executing ViewResult, running view at path "/Views/Category/Create.cshtml". (9707eebe)
2018-04-04T11:26:49.5665888+02:00 0HLCQ1N03CFEB:00000003 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Create (Inventory.Web)" in 390.551ms (afa2e885)
2018-04-04T11:26:49.6764512+02:00 0HLCQ1N03CFEB:00000003 [INF] Request finished in 476.4973ms 200 text/html; charset=utf-8 (791a596a)
2018-04-04T11:26:49.7037283+02:00 0HLCQ1N03CFEE:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/jquery/dist/jquery.js   (ca22a1cb)
2018-04-04T11:26:49.7113124+02:00 0HLCQ1N03CFEG:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/bootstrap/dist/css/bootstrap.css   (ca22a1cb)
2018-04-04T11:26:49.7283468+02:00 0HLCQ1N03CFEH:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44391/js/site.js?v=ji3-IxbEzYWjzzLCGkF1KDjrT2jLbbrSYXw-AhMPNIA   (ca22a1cb)
2018-04-04T11:26:49.7629108+02:00 0HLCQ1N03CFEB:00000004 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js   (ca22a1cb)
2018-04-04T11:26:49.7905136+02:00 0HLCQ1N03CFEE:00000002 [INF] The file "/lib/jquery/dist/jquery.js" was not modified (f1f8d725)
2018-04-04T11:26:49.8350387+02:00 0HLCQ1N03CFEH:00000002 [INF] The file "/js/site.js" was not modified (f1f8d725)
2018-04-04T11:26:49.8535318+02:00 0HLCQ1N03CFEG:00000002 [INF] The file "/lib/bootstrap/dist/css/bootstrap.css" was not modified (f1f8d725)
2018-04-04T11:26:49.8890752+02:00 0HLCQ1N03CFEB:00000004 [INF] The file "/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js" was not modified (f1f8d725)
2018-04-04T11:26:49.8999012+02:00 0HLCQ1N03CFEE:00000002 [INF] Request finished in 155.2412ms 304 application/javascript (791a596a)
2018-04-04T11:26:49.9222675+02:00 0HLCQ1N03CFEG:00000002 [INF] Request finished in 226.7605ms 304 text/css (791a596a)
2018-04-04T11:26:49.9330167+02:00 0HLCQ1N03CFEH:00000002 [INF] Request finished in 207.6088ms 304 application/javascript (791a596a)
2018-04-04T11:26:49.9556731+02:00 0HLCQ1N03CFEB:00000004 [INF] Request finished in 204.1099ms 304 application/javascript (791a596a)
2018-04-04T11:26:50.0095646+02:00 0HLCQ1N03CFED:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/bootstrap/dist/js/bootstrap.js   (ca22a1cb)
2018-04-04T11:26:50.0431210+02:00 0HLCQ1N03CFEF:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44391/css/site.css   (ca22a1cb)
2018-04-04T11:26:50.0756966+02:00 0HLCQ1N03CFEC:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/jquery-validation/dist/jquery.validate.js   (ca22a1cb)
2018-04-04T11:26:50.0842093+02:00 0HLCQ1N03CFEF:00000002 [INF] The file "/css/site.css" was not modified (f1f8d725)
2018-04-04T11:26:50.1283899+02:00 0HLCQ1N03CFED:00000002 [INF] The file "/lib/bootstrap/dist/js/bootstrap.js" was not modified (f1f8d725)
2018-04-04T11:26:50.1906389+02:00 0HLCQ1N03CFEF:00000002 [INF] Request finished in 114.8249ms 304 text/css (791a596a)
2018-04-04T11:26:50.1947085+02:00 0HLCQ1N03CFEC:00000002 [INF] The file "/lib/jquery-validation/dist/jquery.validate.js" was not modified (f1f8d725)
2018-04-04T11:26:50.2244804+02:00 0HLCQ1N03CFED:00000002 [INF] Request finished in 220.4004ms 304 application/javascript (791a596a)
2018-04-04T11:26:50.2381872+02:00 0HLCQ1N03CFEC:00000002 [INF] Request finished in 225.1366ms 304 application/javascript (791a596a)
2018-04-04T11:26:54.7156868+02:00 0HLCQ1N03CFEE:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:44391/category   (ca22a1cb)
2018-04-04T11:26:54.7323922+02:00 0HLCQ1N03CFEE:00000003 [INF] Executing action method "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-04-04T11:26:54.7529300+02:00 0HLCQ1N03CFEE:00000003 [ERR] The view '"Index"' was not found. Searched locations: ["/Views/Category/Index.cshtml", "/Views/Shared/Index.cshtml"] (9bb2756c)
2018-04-04T11:26:54.7673597+02:00 0HLCQ1N03CFEE:00000003 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" in 35.7643ms (afa2e885)
2018-04-04T11:26:54.9256607+02:00 0HLCQ1N03CFEE:00000003 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.InvalidOperationException: The view 'Index' was not found. The following locations were searched:
/Views/Category/Index.cshtml
/Views/Shared/Index.cshtml
   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-04-04T11:26:55.1591436+02:00 0HLCQ1N03CFEE:00000003 [INF] Request finished in 398.4238ms 500 text/html; charset=utf-8 (791a596a)
2018-04-04T11:27:54.5438562+02:00 0HLCQ1PC2O4HM:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/   (ca22a1cb)
2018-04-04T11:27:55.1967165+02:00 0HLCQ1PC2O4HM:00000001 [INF] Executing action method "Inventory.Web.Controllers.HomeController.Index (Inventory.Web)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-04-04T11:27:59.6233629+02:00 0HLCQ1PC2O4HM:00000001 [INF] Executing ViewResult, running view at path "/Views/Home/Index.cshtml". (9707eebe)
2018-04-04T11:28:00.8673703+02:00 0HLCQ1PC2O4HM:00000001 [INF] Executed action "Inventory.Web.Controllers.HomeController.Index (Inventory.Web)" in 5694.1873ms (afa2e885)
2018-04-04T11:28:00.9604973+02:00 0HLCQ1PC2O4HM:00000001 [INF] Request finished in 6497.267ms 200 text/html; charset=utf-8 (791a596a)
2018-04-04T11:28:05.5365153+02:00 0HLCQ1PC2O4HM:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44391/Category/Index   (ca22a1cb)
2018-04-04T11:28:05.5640360+02:00 0HLCQ1PC2O4HM:00000002 [INF] Executing action method "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-04-04T11:28:06.5694733+02:00 0HLCQ1PC2O4HM:00000002 [INF] Executing ViewResult, running view at path "/Views/Category/Index.cshtml". (9707eebe)
2018-04-04T11:28:07.0669210+02:00 0HLCQ1PC2O4HM:00000002 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" in 1508.4883ms (afa2e885)
2018-04-04T11:28:07.4706608+02:00 0HLCQ1PC2O4HM:00000002 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.NullReferenceException: Object reference not set to an instance of an object.
   at AspNetCore._Views_Category_Index_cshtml.<ExecuteAsync>d__8.MoveNext() in C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\Views\Category\Index.cshtml:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageCoreAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-04-04T11:28:07.8689498+02:00 0HLCQ1PC2O4HM:00000002 [INF] Request finished in 2302.1794ms 500 text/html; charset=utf-8 (791a596a)
2018-04-04T11:28:23.9534714+02:00 0HLCQ1PC2O4HM:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:44391/Category/Create   (ca22a1cb)
2018-04-04T11:28:23.9891827+02:00 0HLCQ1PC2O4HM:00000003 [INF] Executing action method "Inventory.Web.Controllers.CategoryController.Create (Inventory.Web)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-04-04T11:28:24.4213713+02:00 0HLCQ1PC2O4HM:00000003 [INF] Executing ViewResult, running view at path "/Views/Category/Create.cshtml". (9707eebe)
2018-04-04T11:28:24.8324354+02:00 0HLCQ1PC2O4HM:00000003 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Create (Inventory.Web)" in 814.6584ms (afa2e885)
2018-04-04T11:28:24.8922087+02:00 0HLCQ1PC2O4HM:00000003 [INF] Request finished in 898.5646ms 200 text/html; charset=utf-8 (791a596a)
2018-04-04T11:29:10.4901065+02:00 0HLCQ1PC2O4HM:00000004 [INF] Request starting HTTP/1.1 POST http://localhost:44391/Category/Create application/x-www-form-urlencoded 262 (ca22a1cb)
2018-04-04T11:29:10.6021376+02:00 0HLCQ1PC2O4HM:00000004 [INF] Executing action method "Inventory.Web.Controllers.CategoryController.Create (Inventory.Web)" with arguments (["Microsoft.AspNetCore.Http.FormCollection"]) - ModelState is Valid (ba7f4ac2)
2018-04-04T11:29:10.6132965+02:00 0HLCQ1PC2O4HM:00000004 [INF] Executing RedirectResult, redirecting to "/Category". (d98d540e)
2018-04-04T11:29:10.6248855+02:00 0HLCQ1PC2O4HM:00000004 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Create (Inventory.Web)" in 98.339ms (afa2e885)
2018-04-04T11:29:10.6445463+02:00 0HLCQ1PC2O4HM:00000004 [INF] Request finished in 150.877ms 302  (791a596a)
2018-04-04T11:29:10.6734455+02:00 0HLCQ1PC2O4HM:00000005 [INF] Request starting HTTP/1.1 GET http://localhost:44391/Category   (ca22a1cb)
2018-04-04T11:29:10.6850287+02:00 0HLCQ1PC2O4HM:00000005 [INF] Executing action method "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-04-04T11:29:10.6984370+02:00 0HLCQ1PC2O4HM:00000005 [INF] Executing ViewResult, running view at path "/Views/Category/Index.cshtml". (9707eebe)
2018-04-04T11:29:10.8093628+02:00 0HLCQ1PC2O4HM:00000005 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" in 122.579ms (afa2e885)
2018-04-04T11:29:11.0500085+02:00 0HLCQ1PC2O4HM:00000005 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.NullReferenceException: Object reference not set to an instance of an object.
   at AspNetCore._Views_Category_Index_cshtml.<ExecuteAsync>d__8.MoveNext() in C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\Views\Category\Index.cshtml:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageCoreAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-04-04T11:29:11.3249109+02:00 0HLCQ1PC2O4HM:00000005 [INF] Request finished in 621.0428ms 500 text/html; charset=utf-8 (791a596a)
2018-04-04T11:31:08.1029978+02:00 0HLCQ1PC2O4HN:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/Category/index   (ca22a1cb)
2018-04-04T11:31:08.1180557+02:00 0HLCQ1PC2O4HN:00000001 [INF] Executing action method "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-04-04T11:31:08.1279236+02:00 0HLCQ1PC2O4HN:00000001 [INF] Executing ViewResult, running view at path "/Views/Category/Index.cshtml". (9707eebe)
2018-04-04T11:31:08.2136174+02:00 0HLCQ1PC2O4HN:00000001 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" in 100.6103ms (afa2e885)
2018-04-04T11:31:08.4413383+02:00 0HLCQ1PC2O4HN:00000001 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.NullReferenceException: Object reference not set to an instance of an object.
   at AspNetCore._Views_Category_Index_cshtml.<ExecuteAsync>d__8.MoveNext() in C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\Views\Category\Index.cshtml:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageCoreAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-04-04T11:31:08.7523302+02:00 0HLCQ1PC2O4HN:00000001 [INF] Request finished in 571.8024ms 500 text/html; charset=utf-8 (791a596a)
2018-04-04T11:39:38.2736147+02:00 0HLCQ1VTQ4T3V:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/   (ca22a1cb)
2018-04-04T11:39:38.7660625+02:00 0HLCQ1VTQ4T3V:00000001 [INF] Executing action method "Inventory.Web.Controllers.HomeController.Index (Inventory.Web)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-04-04T11:39:43.1057287+02:00 0HLCQ1VTQ4T3V:00000001 [INF] Executing ViewResult, running view at path "/Views/Home/Index.cshtml". (9707eebe)
2018-04-04T11:39:43.1659464+02:00 0HLCQ1VTQ4T40:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/Category/Index   (ca22a1cb)
2018-04-04T11:39:43.1985715+02:00 0HLCQ1VTQ4T40:00000001 [INF] Executing action method "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-04-04T11:39:44.3442719+02:00 0HLCQ1VTQ4T3V:00000001 [INF] Executed action "Inventory.Web.Controllers.HomeController.Index (Inventory.Web)" in 5587.7662ms (afa2e885)
2018-04-04T11:39:44.3665262+02:00 0HLCQ1VTQ4T3V:00000001 [INF] Committing the session was canceled. (12038ba6)
2018-04-04T11:39:44.3856070+02:00 0HLCQ1VTQ4T3V:00000001 [INF] Request finished in 6190.093ms 200 text/html; charset=utf-8 (791a596a)
2018-04-04T11:39:44.5009227+02:00 0HLCQ1VTQ4T40:00000001 [INF] Executing ViewResult, running view at path "/Views/Category/Index.cshtml". (9707eebe)
2018-04-04T11:39:44.8424185+02:00 0HLCQ1VTQ4T40:00000001 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" in 1653.9736ms (afa2e885)
2018-04-04T11:39:45.2858650+02:00 0HLCQ1VTQ4T40:00000001 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.NullReferenceException: Object reference not set to an instance of an object.
   at AspNetCore._Views_Category_Index_cshtml.<ExecuteAsync>d__8.MoveNext() in C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\Views\Category\Index.cshtml:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageCoreAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-04-04T11:39:45.6227169+02:00 0HLCQ1VTQ4T40:00000001 [INF] Request finished in 2415.9909ms 500 text/html; charset=utf-8 (791a596a)
2018-04-04T11:40:22.6044147+02:00 0HLCQ1VTQ4T40:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44391/Category/Create   (ca22a1cb)
2018-04-04T11:40:22.6262135+02:00 0HLCQ1VTQ4T40:00000002 [INF] Executing action method "Inventory.Web.Controllers.CategoryController.Create (Inventory.Web)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-04-04T11:40:23.0329256+02:00 0HLCQ1VTQ4T40:00000002 [INF] Executing ViewResult, running view at path "/Views/Category/Create.cshtml". (9707eebe)
2018-04-04T11:40:23.6471425+02:00 0HLCQ1VTQ4T40:00000002 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Create (Inventory.Web)" in 852.7605ms (afa2e885)
2018-04-04T11:40:23.6640305+02:00 0HLCQ1VTQ4T41:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/bootstrap/dist/css/bootstrap.css   (ca22a1cb)
2018-04-04T11:40:23.6736503+02:00 0HLCQ1VTQ4T45:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/jquery-validation/dist/jquery.validate.js   (ca22a1cb)
2018-04-04T11:40:23.7022719+02:00 0HLCQ1VTQ4T40:00000002 [INF] Request finished in 1058.6576ms 200 text/html; charset=utf-8 (791a596a)
2018-04-04T11:40:23.7510023+02:00 0HLCQ1VTQ4T42:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/jquery/dist/jquery.js   (ca22a1cb)
2018-04-04T11:40:23.7627537+02:00 0HLCQ1VTQ4T45:00000001 [INF] The file "/lib/jquery-validation/dist/jquery.validate.js" was not modified (f1f8d725)
2018-04-04T11:40:23.8010200+02:00 0HLCQ1VTQ4T42:00000001 [INF] The file "/lib/jquery/dist/jquery.js" was not modified (f1f8d725)
2018-04-04T11:40:23.8283659+02:00 0HLCQ1VTQ4T43:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/css/site.css   (ca22a1cb)
2018-04-04T11:40:23.8668664+02:00 0HLCQ1VTQ4T45:00000001 [INF] Request finished in 146.6379ms 304 application/javascript (791a596a)
2018-04-04T11:40:23.9038423+02:00 0HLCQ1VTQ4T44:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js   (ca22a1cb)
2018-04-04T11:40:23.9244442+02:00 0HLCQ1VTQ4T43:00000001 [INF] Sending file. Request path: '"/css/site.css"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\css\site.css"' (27b0a520)
2018-04-04T11:40:23.9447480+02:00 0HLCQ1VTQ4T44:00000001 [INF] The file "/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js" was not modified (f1f8d725)
2018-04-04T11:40:23.9640216+02:00 0HLCQ1VTQ4T41:00000001 [INF] Sending file. Request path: '"/lib/bootstrap/dist/css/bootstrap.css"'. Physical path: '"C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\wwwroot\lib\bootstrap\dist\css\bootstrap.css"' (27b0a520)
2018-04-04T11:40:23.9855338+02:00 0HLCQ1VTQ4T42:00000001 [INF] Request finished in 94.7718ms 304 application/javascript (791a596a)
2018-04-04T11:40:23.9985240+02:00 0HLCQ1VTQ4T44:00000001 [INF] Request finished in 63.7767ms 304 application/javascript (791a596a)
2018-04-04T11:40:24.0379969+02:00 0HLCQ1VTQ4T43:00000001 [INF] Request finished in 319.5631ms 200 text/css (791a596a)
2018-04-04T11:40:24.1100558+02:00 0HLCQ1VTQ4T47:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/lib/bootstrap/dist/js/bootstrap.js   (ca22a1cb)
2018-04-04T11:40:24.1553150+02:00 0HLCQ1VTQ4T46:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44391/js/site.js?v=ji3-IxbEzYWjzzLCGkF1KDjrT2jLbbrSYXw-AhMPNIA   (ca22a1cb)
2018-04-04T11:40:24.2062252+02:00 0HLCQ1VTQ4T41:00000001 [INF] Request finished in 479.8489ms 200 text/css (791a596a)
2018-04-04T11:40:24.2198593+02:00 0HLCQ1VTQ4T47:00000001 [INF] The file "/lib/bootstrap/dist/js/bootstrap.js" was not modified (f1f8d725)
2018-04-04T11:40:24.2237245+02:00 0HLCQ1VTQ4T46:00000001 [INF] The file "/js/site.js" was not modified (f1f8d725)
2018-04-04T11:40:24.2658998+02:00 0HLCQ1VTQ4T47:00000001 [INF] Request finished in 212.2969ms 304 application/javascript (791a596a)
2018-04-04T11:40:24.2755905+02:00 0HLCQ1VTQ4T46:00000001 [INF] Request finished in 236.358ms 304 application/javascript (791a596a)
2018-04-04T11:40:31.3410898+02:00 0HLCQ1VTQ4T40:00000003 [INF] Request starting HTTP/1.1 POST http://localhost:44391/Category/Create application/x-www-form-urlencoded 260 (ca22a1cb)
2018-04-04T11:40:31.4487291+02:00 0HLCQ1VTQ4T40:00000003 [INF] Executing action method "Inventory.Web.Controllers.CategoryController.Create (Inventory.Web)" with arguments (["Microsoft.AspNetCore.Http.FormCollection"]) - ModelState is Valid (ba7f4ac2)
2018-04-04T11:40:31.4601178+02:00 0HLCQ1VTQ4T40:00000003 [INF] Executing RedirectResult, redirecting to "/Category". (d98d540e)
2018-04-04T11:40:31.4687630+02:00 0HLCQ1VTQ4T40:00000003 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Create (Inventory.Web)" in 92.9052ms (afa2e885)
2018-04-04T11:40:31.4853301+02:00 0HLCQ1VTQ4T40:00000003 [INF] Request finished in 137.9257ms 302  (791a596a)
2018-04-04T11:40:31.4981535+02:00 0HLCQ1VTQ4T45:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44391/Category   (ca22a1cb)
2018-04-04T11:40:31.5070633+02:00 0HLCQ1VTQ4T45:00000002 [INF] Executing action method "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-04-04T11:40:31.5169522+02:00 0HLCQ1VTQ4T45:00000002 [INF] Executing ViewResult, running view at path "/Views/Category/Index.cshtml". (9707eebe)
2018-04-04T11:40:31.6002657+02:00 0HLCQ1VTQ4T45:00000002 [INF] Executed action "Inventory.Web.Controllers.CategoryController.Index (Inventory.Web)" in 88.318ms (afa2e885)
2018-04-04T11:40:31.8752426+02:00 0HLCQ1VTQ4T45:00000002 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.NullReferenceException: Object reference not set to an instance of an object.
   at AspNetCore._Views_Category_Index_cshtml.<ExecuteAsync>d__8.MoveNext() in C:\Users\Ola\Documents\GitHub\Inventory\Inventory\Inventory.Web\Views\Category\Index.cshtml:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageCoreAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-04-04T11:40:32.0845524+02:00 0HLCQ1VTQ4T45:00000002 [INF] Request finished in 575.4811ms 500 text/html; charset=utf-8 (791a596a)
